apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: team-researchops
  name: reops-fastapi
  namespace: team-researchops
spec:
  envFrom:
    - secret: fastapi-secrets
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - ipv4: 34.88.239.95
  ingresses:
    - https://fastapi.ansatt.nav.no
    - https://fastapi.intern.nav.no
    - https://fastapi.nav.no/stats
  liveness:
    path: /api/isalive
    initialDelay: 20
    periodSeconds: 6
    timeout: 2
  readiness:
    path: /api/isready
    initialDelay: 20
    periodSeconds: 6
    timeout: 10
