apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: team-researchops
  name: reops-fastapi
  namespace: team-researchops
spec:
  env:
    - name: "DATABASE_URL"
      value: "$(NAIS_DATABASE_REOPS_FASTAPI_REOPS_FASTAPI_URL)"
    - name: "SKIP_DB_CHECK"
      value: "false"
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - ipv4: 34.88.239.95
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: reops-fastapi
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - https://fastapi.ansatt.nav.no
    - https://fastapi.intern.nav.no
    - https://fastapi.nav.no/api/send
  liveness:
    path: /api/isalive
    initialDelay: 20
    periodSeconds: 6
    timeout: 2
  readiness:
    path: /api/isready
    initialDelay: 20
    periodSeconds: 6
    timeout: 10
